package literature.review.app.model;
// Generated Dec 20, 2019, 7:40:21 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * AuthorPublications generated by hbm2java
 */
@Entity
@Table(name = "author_publications", schema = "slr")
@JsonIgnoreProperties({"hibernateLazyinitializer","handler"})
public class AuthorPublications implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private long id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "author_id")
	@JsonIgnore
	private Authors authors;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "publication_id")
	@JsonIgnore
	private Publications publications;
	
	@Column(name = "herarchy")
	private Integer herarchy;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "create_at", length = 13)
	private Date createAt;

	public AuthorPublications() {
	}

	public AuthorPublications(long id) {
		this.id = id;
	}

	public AuthorPublications(long id, Authors authors, Publications publications, Integer herarchy, Date createAt) {
		this.id = id;
		this.authors = authors;
		this.publications = publications;
		this.herarchy = herarchy;
		this.createAt = createAt;
	}


	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}


	public Authors getAuthors() {
		return this.authors;
	}

	public void setAuthors(Authors authors) {
		this.authors = authors;
	}

	public Publications getPublications() {
		return this.publications;
	}

	public void setPublications(Publications publications) {
		this.publications = publications;
	}


	public Integer getHerarchy() {
		return this.herarchy;
	}

	public void setHerarchy(Integer herarchy) {
		this.herarchy = herarchy;
	}


	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

}
