package literature.review.app.model;
// Generated Dec 20, 2019, 7:40:21 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Editions generated by hbm2java
 */
@Entity
@Table(name = "editions", schema = "slr")
@JsonIgnoreProperties({"hibernateLazyinitializer","handler"})
public class Editions implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private long id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "conference_id")
	@JsonIgnore
	private Conferences conferences;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "publisher_id")
	@JsonIgnore
	private Publishers publishers;
	
	private String editors;
	private Integer year;
	private String number;
	private Date createdAt;
	
	@OneToMany(fetch = FetchType.LAZY,cascade = CascadeType.ALL, mappedBy = "editions")
	private Set<ConferencePapers> conferecePaperses = new HashSet<ConferencePapers>(0);
	
	@OneToMany(fetch = FetchType.LAZY,cascade = CascadeType.ALL, mappedBy = "editions")
	private Set<ConferenceEditorials> confereceEditorialses = new HashSet<ConferenceEditorials>(0);

	public Editions() {
	}

	public Editions(long id) {
		this.id = id;
	}

	public Editions(long id, Conferences conferences, Publishers publishers, String editors, Integer year,
			String number, Date createdAt, Set<ConferencePapers> conferecePaperses,
			Set<ConferenceEditorials> confereceEditorialses) {
		this.id = id;
		this.conferences = conferences;
		this.publishers = publishers;
		this.editors = editors;
		this.year = year;
		this.number = number;
		this.createdAt = createdAt;
		this.conferecePaperses = conferecePaperses;
		this.confereceEditorialses = confereceEditorialses;
	}


	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	
	public Conferences getConferences() {
		return this.conferences;
	}

	public void setConferences(Conferences conferences) {
		this.conferences = conferences;
	}

	
	public Publishers getPublishers() {
		return this.publishers;
	}

	public void setPublishers(Publishers publishers) {
		this.publishers = publishers;
	}

	@Column(name = "editors")
	public String getEditors() {
		return this.editors;
	}

	public void setEditors(String editors) {
		this.editors = editors;
	}

	@Column(name = "year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "number", length = 100)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", length = 13)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}


	public Set<ConferencePapers> getConferecePaperses() {
		return this.conferecePaperses;
	}

	public void setConferecePaperses(Set<ConferencePapers> conferecePaperses) {
		this.conferecePaperses = conferecePaperses;
	}

	
	public Set<ConferenceEditorials> getConfereceEditorialses() {
		return this.confereceEditorialses;
	}

	public void setConfereceEditorialses(Set<ConferenceEditorials> confereceEditorialses) {
		this.confereceEditorialses = confereceEditorialses;
	}

}
