package app.configuration.db.tables;
// Generated Sep 27, 2019, 11:41:57 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuthorPublications generated by hbm2java
 */
@Entity
@Table(name = "author_publications")
public class AuthorPublications implements java.io.Serializable {

	private long id;
	private Author author;
	private Publication publication;
	private Integer herarchy;
	private Date createAt;

	public AuthorPublications() {
	}

	public AuthorPublications(long id) {
		this.id = id;
	}

	public AuthorPublications(long id, Author author, Publication publication, Integer herarchy, Date createAt) {
		this.id = id;
		this.author = author;
		this.publication = publication;
		this.herarchy = herarchy;
		this.createAt = createAt;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "author_id")
	public Author getAuthor() {
		return this.author;
	}

	public void setAuthor(Author author) {
		this.author = author;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "publication_id")
	public Publication getPublication() {
		return this.publication;
	}

	public void setPublication(Publication publication) {
		this.publication = publication;
	}

	@Column(name = "herarchy")
	public Integer getHerarchy() {
		return this.herarchy;
	}

	public void setHerarchy(Integer herarchy) {
		this.herarchy = herarchy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_at", length = 29)
	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

}
