package app.configuration.db.tables;
// Generated Sep 27, 2019, 11:41:57 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Conference generated by hbm2java
 */
@Entity
@Table(name = "conference")
public class Conference implements java.io.Serializable {

	private int id;
	private String description;
	private Set<Edition> editions = new HashSet<Edition>(0);

	public Conference() {
	}

	public Conference(int id) {
		this.id = id;
	}

	public Conference(int id, String description, Set<Edition> editions) {
		this.id = id;
		this.description = description;
		this.editions = editions;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conference")
	public Set<Edition> getEditions() {
		return this.editions;
	}

	public void setEditions(Set<Edition> editions) {
		this.editions = editions;
	}

}
