package app.configuration.db.tables;
// Generated Sep 27, 2019, 11:41:57 PM by Hibernate Tools 5.2.12.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DblpDocumentId generated by hbm2java
 */
@Embeddable
public class DblpDocumentId implements java.io.Serializable {

	private int id;
	private String keyDblp;
	private Serializable authors;
	private String docType;
	private String editor;
	private String booktitle;
	private String pages;
	private Integer year;
	private String title;
	private String address;
	private String journal;
	private String volume;
	private String number;
	private String month;
	private String url;
	private String ee;
	private String cdrom;
	private String cite;
	private String publisher;
	private String note;
	private String crossref;
	private String isbn;
	private String series;
	private String school;
	private String chapter;
	private String publnr;
	private Serializable unknowFields;
	private Serializable unknowAtts;
	private String mdate;
	private Boolean updated;

	public DblpDocumentId() {
	}

	public DblpDocumentId(int id) {
		this.id = id;
	}

	public DblpDocumentId(int id, String keyDblp, Serializable authors, String docType, String editor, String booktitle,
			String pages, Integer year, String title, String address, String journal, String volume, String number,
			String month, String url, String ee, String cdrom, String cite, String publisher, String note,
			String crossref, String isbn, String series, String school, String chapter, String publnr,
			Serializable unknowFields, Serializable unknowAtts, String mdate, Boolean updated) {
		this.id = id;
		this.keyDblp = keyDblp;
		this.authors = authors;
		this.docType = docType;
		this.editor = editor;
		this.booktitle = booktitle;
		this.pages = pages;
		this.year = year;
		this.title = title;
		this.address = address;
		this.journal = journal;
		this.volume = volume;
		this.number = number;
		this.month = month;
		this.url = url;
		this.ee = ee;
		this.cdrom = cdrom;
		this.cite = cite;
		this.publisher = publisher;
		this.note = note;
		this.crossref = crossref;
		this.isbn = isbn;
		this.series = series;
		this.school = school;
		this.chapter = chapter;
		this.publnr = publnr;
		this.unknowFields = unknowFields;
		this.unknowAtts = unknowAtts;
		this.mdate = mdate;
		this.updated = updated;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "key_dblp", length = 100)
	public String getKeyDblp() {
		return this.keyDblp;
	}

	public void setKeyDblp(String keyDblp) {
		this.keyDblp = keyDblp;
	}

	@Column(name = "authors")
	public Serializable getAuthors() {
		return this.authors;
	}

	public void setAuthors(Serializable authors) {
		this.authors = authors;
	}

	@Column(name = "doc_type", length = 100)
	public String getDocType() {
		return this.docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}

	@Column(name = "editor", length = 100)
	public String getEditor() {
		return this.editor;
	}

	public void setEditor(String editor) {
		this.editor = editor;
	}

	@Column(name = "booktitle", length = 250)
	public String getBooktitle() {
		return this.booktitle;
	}

	public void setBooktitle(String booktitle) {
		this.booktitle = booktitle;
	}

	@Column(name = "pages", length = 50)
	public String getPages() {
		return this.pages;
	}

	public void setPages(String pages) {
		this.pages = pages;
	}

	@Column(name = "year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "journal")
	public String getJournal() {
		return this.journal;
	}

	public void setJournal(String journal) {
		this.journal = journal;
	}

	@Column(name = "volume", length = 100)
	public String getVolume() {
		return this.volume;
	}

	public void setVolume(String volume) {
		this.volume = volume;
	}

	@Column(name = "number", length = 50)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "month", length = 50)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "ee")
	public String getEe() {
		return this.ee;
	}

	public void setEe(String ee) {
		this.ee = ee;
	}

	@Column(name = "cdrom")
	public String getCdrom() {
		return this.cdrom;
	}

	public void setCdrom(String cdrom) {
		this.cdrom = cdrom;
	}

	@Column(name = "cite")
	public String getCite() {
		return this.cite;
	}

	public void setCite(String cite) {
		this.cite = cite;
	}

	@Column(name = "publisher")
	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "crossref")
	public String getCrossref() {
		return this.crossref;
	}

	public void setCrossref(String crossref) {
		this.crossref = crossref;
	}

	@Column(name = "isbn")
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "series")
	public String getSeries() {
		return this.series;
	}

	public void setSeries(String series) {
		this.series = series;
	}

	@Column(name = "school")
	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	@Column(name = "chapter")
	public String getChapter() {
		return this.chapter;
	}

	public void setChapter(String chapter) {
		this.chapter = chapter;
	}

	@Column(name = "publnr")
	public String getPublnr() {
		return this.publnr;
	}

	public void setPublnr(String publnr) {
		this.publnr = publnr;
	}

	@Column(name = "unknow_fields")
	public Serializable getUnknowFields() {
		return this.unknowFields;
	}

	public void setUnknowFields(Serializable unknowFields) {
		this.unknowFields = unknowFields;
	}

	@Column(name = "unknow_atts")
	public Serializable getUnknowAtts() {
		return this.unknowAtts;
	}

	public void setUnknowAtts(Serializable unknowAtts) {
		this.unknowAtts = unknowAtts;
	}

	@Column(name = "mdate", length = 100)
	public String getMdate() {
		return this.mdate;
	}

	public void setMdate(String mdate) {
		this.mdate = mdate;
	}

	@Column(name = "updated")
	public Boolean getUpdated() {
		return this.updated;
	}

	public void setUpdated(Boolean updated) {
		this.updated = updated;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DblpDocumentId))
			return false;
		DblpDocumentId castOther = (DblpDocumentId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getKeyDblp() == castOther.getKeyDblp()) || (this.getKeyDblp() != null
						&& castOther.getKeyDblp() != null && this.getKeyDblp().equals(castOther.getKeyDblp())))
				&& ((this.getAuthors() == castOther.getAuthors()) || (this.getAuthors() != null
						&& castOther.getAuthors() != null && this.getAuthors().equals(castOther.getAuthors())))
				&& ((this.getDocType() == castOther.getDocType()) || (this.getDocType() != null
						&& castOther.getDocType() != null && this.getDocType().equals(castOther.getDocType())))
				&& ((this.getEditor() == castOther.getEditor()) || (this.getEditor() != null
						&& castOther.getEditor() != null && this.getEditor().equals(castOther.getEditor())))
				&& ((this.getBooktitle() == castOther.getBooktitle()) || (this.getBooktitle() != null
						&& castOther.getBooktitle() != null && this.getBooktitle().equals(castOther.getBooktitle())))
				&& ((this.getPages() == castOther.getPages()) || (this.getPages() != null
						&& castOther.getPages() != null && this.getPages().equals(castOther.getPages())))
				&& ((this.getYear() == castOther.getYear()) || (this.getYear() != null && castOther.getYear() != null
						&& this.getYear().equals(castOther.getYear())))
				&& ((this.getTitle() == castOther.getTitle()) || (this.getTitle() != null
						&& castOther.getTitle() != null && this.getTitle().equals(castOther.getTitle())))
				&& ((this.getAddress() == castOther.getAddress()) || (this.getAddress() != null
						&& castOther.getAddress() != null && this.getAddress().equals(castOther.getAddress())))
				&& ((this.getJournal() == castOther.getJournal()) || (this.getJournal() != null
						&& castOther.getJournal() != null && this.getJournal().equals(castOther.getJournal())))
				&& ((this.getVolume() == castOther.getVolume()) || (this.getVolume() != null
						&& castOther.getVolume() != null && this.getVolume().equals(castOther.getVolume())))
				&& ((this.getNumber() == castOther.getNumber()) || (this.getNumber() != null
						&& castOther.getNumber() != null && this.getNumber().equals(castOther.getNumber())))
				&& ((this.getMonth() == castOther.getMonth()) || (this.getMonth() != null
						&& castOther.getMonth() != null && this.getMonth().equals(castOther.getMonth())))
				&& ((this.getUrl() == castOther.getUrl()) || (this.getUrl() != null && castOther.getUrl() != null
						&& this.getUrl().equals(castOther.getUrl())))
				&& ((this.getEe() == castOther.getEe()) || (this.getEe() != null && castOther.getEe() != null
						&& this.getEe().equals(castOther.getEe())))
				&& ((this.getCdrom() == castOther.getCdrom()) || (this.getCdrom() != null
						&& castOther.getCdrom() != null && this.getCdrom().equals(castOther.getCdrom())))
				&& ((this.getCite() == castOther.getCite()) || (this.getCite() != null && castOther.getCite() != null
						&& this.getCite().equals(castOther.getCite())))
				&& ((this.getPublisher() == castOther.getPublisher()) || (this.getPublisher() != null
						&& castOther.getPublisher() != null && this.getPublisher().equals(castOther.getPublisher())))
				&& ((this.getNote() == castOther.getNote()) || (this.getNote() != null && castOther.getNote() != null
						&& this.getNote().equals(castOther.getNote())))
				&& ((this.getCrossref() == castOther.getCrossref()) || (this.getCrossref() != null
						&& castOther.getCrossref() != null && this.getCrossref().equals(castOther.getCrossref())))
				&& ((this.getIsbn() == castOther.getIsbn()) || (this.getIsbn() != null && castOther.getIsbn() != null
						&& this.getIsbn().equals(castOther.getIsbn())))
				&& ((this.getSeries() == castOther.getSeries()) || (this.getSeries() != null
						&& castOther.getSeries() != null && this.getSeries().equals(castOther.getSeries())))
				&& ((this.getSchool() == castOther.getSchool()) || (this.getSchool() != null
						&& castOther.getSchool() != null && this.getSchool().equals(castOther.getSchool())))
				&& ((this.getChapter() == castOther.getChapter()) || (this.getChapter() != null
						&& castOther.getChapter() != null && this.getChapter().equals(castOther.getChapter())))
				&& ((this.getPublnr() == castOther.getPublnr()) || (this.getPublnr() != null
						&& castOther.getPublnr() != null && this.getPublnr().equals(castOther.getPublnr())))
				&& ((this.getUnknowFields() == castOther.getUnknowFields())
						|| (this.getUnknowFields() != null && castOther.getUnknowFields() != null
								&& this.getUnknowFields().equals(castOther.getUnknowFields())))
				&& ((this.getUnknowAtts() == castOther.getUnknowAtts()) || (this.getUnknowAtts() != null
						&& castOther.getUnknowAtts() != null && this.getUnknowAtts().equals(castOther.getUnknowAtts())))
				&& ((this.getMdate() == castOther.getMdate()) || (this.getMdate() != null
						&& castOther.getMdate() != null && this.getMdate().equals(castOther.getMdate())))
				&& ((this.getUpdated() == castOther.getUpdated()) || (this.getUpdated() != null
						&& castOther.getUpdated() != null && this.getUpdated().equals(castOther.getUpdated())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getKeyDblp() == null ? 0 : this.getKeyDblp().hashCode());
		result = 37 * result + (getAuthors() == null ? 0 : this.getAuthors().hashCode());
		result = 37 * result + (getDocType() == null ? 0 : this.getDocType().hashCode());
		result = 37 * result + (getEditor() == null ? 0 : this.getEditor().hashCode());
		result = 37 * result + (getBooktitle() == null ? 0 : this.getBooktitle().hashCode());
		result = 37 * result + (getPages() == null ? 0 : this.getPages().hashCode());
		result = 37 * result + (getYear() == null ? 0 : this.getYear().hashCode());
		result = 37 * result + (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result + (getAddress() == null ? 0 : this.getAddress().hashCode());
		result = 37 * result + (getJournal() == null ? 0 : this.getJournal().hashCode());
		result = 37 * result + (getVolume() == null ? 0 : this.getVolume().hashCode());
		result = 37 * result + (getNumber() == null ? 0 : this.getNumber().hashCode());
		result = 37 * result + (getMonth() == null ? 0 : this.getMonth().hashCode());
		result = 37 * result + (getUrl() == null ? 0 : this.getUrl().hashCode());
		result = 37 * result + (getEe() == null ? 0 : this.getEe().hashCode());
		result = 37 * result + (getCdrom() == null ? 0 : this.getCdrom().hashCode());
		result = 37 * result + (getCite() == null ? 0 : this.getCite().hashCode());
		result = 37 * result + (getPublisher() == null ? 0 : this.getPublisher().hashCode());
		result = 37 * result + (getNote() == null ? 0 : this.getNote().hashCode());
		result = 37 * result + (getCrossref() == null ? 0 : this.getCrossref().hashCode());
		result = 37 * result + (getIsbn() == null ? 0 : this.getIsbn().hashCode());
		result = 37 * result + (getSeries() == null ? 0 : this.getSeries().hashCode());
		result = 37 * result + (getSchool() == null ? 0 : this.getSchool().hashCode());
		result = 37 * result + (getChapter() == null ? 0 : this.getChapter().hashCode());
		result = 37 * result + (getPublnr() == null ? 0 : this.getPublnr().hashCode());
		result = 37 * result + (getUnknowFields() == null ? 0 : this.getUnknowFields().hashCode());
		result = 37 * result + (getUnknowAtts() == null ? 0 : this.getUnknowAtts().hashCode());
		result = 37 * result + (getMdate() == null ? 0 : this.getMdate().hashCode());
		result = 37 * result + (getUpdated() == null ? 0 : this.getUpdated().hashCode());
		return result;
	}

}
