package app.configuration.db.tables;
// Generated Sep 27, 2019, 11:41:57 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Keyword generated by hbm2java
 */
@Entity
@Table(name = "keyword")
public class Keyword implements java.io.Serializable {

	private int id;
	private String name;
	private Set<PublicationKeywords> publicationKeywordses = new HashSet<PublicationKeywords>(0);

	public Keyword() {
	}

	public Keyword(int id) {
		this.id = id;
	}

	public Keyword(int id, String name, Set<PublicationKeywords> publicationKeywordses) {
		this.id = id;
		this.name = name;
		this.publicationKeywordses = publicationKeywordses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(orphanRemoval=true, cascade=CascadeType.ALL,fetch = FetchType.LAZY, mappedBy = "keyword")
	public Set<PublicationKeywords> getPublicationKeywordses() {
		return this.publicationKeywordses;
	}

	public void setPublicationKeywordses(Set<PublicationKeywords> publicationKeywordses) {
		this.publicationKeywordses = publicationKeywordses;
	}

}
