package app.configuration.db.tables;
// Generated Sep 27, 2019, 11:41:57 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Publisher generated by hbm2java
 */
@Entity
@Table(name = "publisher")
public class Publisher implements java.io.Serializable {

	private long id;
	private String description;
	private String state;
	private Set<BookChapter> bookChapters = new HashSet<BookChapter>(0);
	private Set<Book> books = new HashSet<Book>(0);

	public Publisher() {
	}

	public Publisher(long id) {
		this.id = id;
	}

	public Publisher(long id, String description, String state, Set<BookChapter> bookChapters, Set<Book> books) {
		this.id = id;
		this.description = description;
		this.state = state;
		this.bookChapters = bookChapters;
		this.books = books;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "state", length = 80)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publisher")
	public Set<BookChapter> getBookChapters() {
		return this.bookChapters;
	}

	public void setBookChapters(Set<BookChapter> bookChapters) {
		this.bookChapters = bookChapters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publisher")
	public Set<Book> getBooks() {
		return this.books;
	}

	public void setBooks(Set<Book> books) {
		this.books = books;
	}

}
