package app.configuration.db.tables;
// Generated Sep 27, 2019, 11:41:57 PM by Hibernate Tools 5.2.12.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "test")
public class Test implements java.io.Serializable {

	private int id;
	private Serializable cadena;
	private Integer numero;

	public Test() {
	}

	public Test(int id) {
		this.id = id;
	}

	public Test(int id, Serializable cadena, Integer numero) {
		this.id = id;
		this.cadena = cadena;
		this.numero = numero;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "cadena")
	public Serializable getCadena() {
		return this.cadena;
	}

	public void setCadena(Serializable cadena) {
		this.cadena = cadena;
	}

	@Column(name = "numero")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

}
