package app.configuration.db.tables;
// Generated Sep 27, 2019, 11:41:57 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VolumeNumber generated by hbm2java
 */
@Entity
@Table(name = "volume_number")
public class VolumeNumber implements java.io.Serializable {

	private int id;
	private Journal journal;
	private Integer volume;
	private Integer number;
	private Set<JournalEditorial> journalEditorials = new HashSet<JournalEditorial>(0);
	private Set<JournalPaper> journalPapers = new HashSet<JournalPaper>(0);

	public VolumeNumber() {
	}

	public VolumeNumber(int id) {
		this.id = id;
	}

	public VolumeNumber(int id, Journal journal, Integer volume, Integer number,
			Set<JournalEditorial> journalEditorials, Set<JournalPaper> journalPapers) {
		this.id = id;
		this.journal = journal;
		this.volume = volume;
		this.number = number;
		this.journalEditorials = journalEditorials;
		this.journalPapers = journalPapers;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "journal_id")
	public Journal getJournal() {
		return this.journal;
	}

	public void setJournal(Journal journal) {
		this.journal = journal;
	}

	@Column(name = "volume")
	public Integer getVolume() {
		return this.volume;
	}

	public void setVolume(Integer volume) {
		this.volume = volume;
	}

	@Column(name = "number")
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "volumeNumber")
	public Set<JournalEditorial> getJournalEditorials() {
		return this.journalEditorials;
	}

	public void setJournalEditorials(Set<JournalEditorial> journalEditorials) {
		this.journalEditorials = journalEditorials;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "volumeNumber")
	public Set<JournalPaper> getJournalPapers() {
		return this.journalPapers;
	}

	public void setJournalPapers(Set<JournalPaper> journalPapers) {
		this.journalPapers = journalPapers;
	}

}
