package app.configuration.db.tables;
// Generated Sep 27, 2019, 11:41:57 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Journal generated by hbm2java
 */
@Entity
@Table(name = "journal")
public class Journal implements java.io.Serializable {

	private int id;
	private String description;
	private Set<VolumeNumber> volumeNumbers = new HashSet<VolumeNumber>(0);

	public Journal() {
	}

	public Journal(int id) {
		this.id = id;
	}

	public Journal(int id, String description, Set<VolumeNumber> volumeNumbers) {
		this.id = id;
		this.description = description;
		this.volumeNumbers = volumeNumbers;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "journal")
	public Set<VolumeNumber> getVolumeNumbers() {
		return this.volumeNumbers;
	}

	public void setVolumeNumbers(Set<VolumeNumber> volumeNumbers) {
		this.volumeNumbers = volumeNumbers;
	}

}
